# https://pre-commit.com/
# poetry add pre-commit --dev
# poetry run pre-commit install
repos:
  # making isort compatible with black
  # see https://github.com/PyCQA/isort/issues/1518
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: ^(.vscode/|other/folder/) # weird errors with .vscode/*.json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^((.*)\.(ipynb|otherext)) # avoid reformat notebooks everytime
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        # args: ["--profile", "black"] set up in pyproject.toml
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
