# ReadTheDocs configuration file
# see https://docs.readthedocs.io/en/stable/config-file/v2.html

# If you wish to deploy your documentation using ReadTheDocs at
# https://your_project_name.readthedocs.io/
# Create a ReadTheDocs account using your GitHub profile
# https://readthedocs.org/accounts/login/
# This will make sure ReadTheDocs and GitHub are linked
# https://docs.readthedocs.io/en/stable/connected-accounts.html
# so that GitHub projects can be easily imported on ReadTheDocs
# https://docs.readthedocs.io/en/stable/intro/import-guide.html
# Once your project is imported, simply

# Alternatively you can use GitHub Pages to deploy your documentation
# see also the .github/workflows/docs.yml workflow file

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  # dirhtml, singlehtml
  fail_on_warning: false

# Configuration for Mkdocs documentation.
# mkdocs:
#   configuration: docs/mkdocs.yml
#   fail_on_warning: false

# Build formats
formats: []
# formats:
#   - pdf
#   - epub
#   - htmlzip
# formats: all

# Configuration for Conda support.
# https://docs.readthedocs.io/en/stable/guides/conda.html
# conda:
#   environment: environment.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    # - requirements: docs/requirements.txt
    - method: pip
      # pip install .[docs] see [tool.poetry.extras] in pyproject.toml
      path: .
      extra_requirements:
        - docs
    # - method: setuptools
    #   path: another/package
  system_packages: true
