# See https://python-poetry.org/docs/configuration

[virtualenvs]
# poetry config virtualenvs.create true --local
create = true
# poetry config virtualenvs.in-project true --local
in-project = true
# poetry config virtualenvs.prefer-active-python true --local
prefer-active-python = true
